apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingest-pvc
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.ingest.size }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library-pvc
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.library.size }}

